version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 483639178502.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t docker build -t my-ecr-repo .
      - docker tag my-ecr-repo:latest 483639178502.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 483639178502.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:latest
