version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - set -eu
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t amsantana-dockerhub .
      - docker tag amsantana-dockerhub:latest 196213906354.dkr.ecr.us-west-2.amazonaws.com/amsantana-dockerhub:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 196213906354.dkr.ecr.us-west-2.amazonaws.com/amsantana-dockerhub:latest
